# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Fp70iKszbpTry5hRX-rpIpjyg_ifUCQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np, pandas as pd
import matplotlib.pyplot as plt, seaborn as sns

df = pd.read_csv('data/games.csv', lineterminator='\n')

df.shape

df.head().transpose()

plt.rc('xtick', labelsize=14)
plt.rc('ytick', labelsize=14)
sns.set_style(style='whitegrid')

"""### General

__Which console has more games titles ?__
"""

df.groupby('platform')['title'].count().sort_values(ascending=False).plot.bar(figsize=(10, 6), rot=0);

"""Given release date let's add two columns with year and month information"""

df['release_date'] = pd.to_datetime(df['release_date'])
df['month'] = df['release_date'].dt.month
df['year'] = df['release_date'].dt.year

"""EA Sports appears also as 'EA Sports, EA Vancouver' and 'EA Vancouver'. Let's unify the names"""

df.loc[df['developer'] == 'EA Sports, EA Vancouver', 'developer'] = 'EA Sports'
df.loc[df['developer'] == 'EA Vancouver', 'developer'] = 'EA Sports'

"""In order to perform analysis related to scores, we need to use those games with reviews"""

tmp = df.loc[(df['meta_overview'] != 'No score yet') & (df['user_overview'] != 'No user score yet')].copy()

"""__Which console has best average scores ?__"""

tmp.groupby('platform')['meta_score', 'n_user_score'].mean().sort_values('meta_score', ascending=False).plot.bar(figsize=(10, 6), rot=0);

"""Let's compare metacritics scores vs user scores. (metacritics scores are made by specialized critics sites while user scores by people registered on metacritic.com)"""

tmp[['meta_score']].plot.hist(bins=25, figsize=(12, 6));

tmp[['n_user_score']].plot.hist(bins=25, figsize=(12, 6));

"""Meta scores tend to be higher than user scores"""

fig, ax = plt.subplots(figsize=(12, 8))
ax.plot([0, 100], [0, 100])
tmp.plot.scatter(x='n_user_score', y='meta_score', ax=ax, alpha=0.25);

mo = tmp.groupby('meta_overview')['title'].count()
mo.name = 'meta_overview'
uo = tmp.groupby('user_overview')['title'].count()
uo.name = 'user_overview'
pd.concat([mo, uo], axis=1).sort_values('meta_overview', ascending=False).plot.bar(figsize=(12, 6));

"""We confirm that there are more 'Generally favorable reviews' in meta scores and more 'Generally unfavorable reviews' in user scores. <br>Users tend to be more critic in their reviews than specialized sites (paid reviews ?)

__How many new titles were released since 2014 ?__

Here we compare just PlayStation 4 and Xbox One because both platforms were announced the same year (2013). On the other hand Nintendo Switch in 2016
"""

df.loc[(df['year'] > 2013) & (df['year'] < 2018) & (df['platform'] != 'Switch')].groupby(['year', 'platform'])['title'].count().unstack().plot.bar(figsize=(10, 6));

"""__When are new titles released ?__"""

df.groupby(['year', 'month'])['title'].count().groupby('month').mean().plot(figsize=(12, 6));

"""There's a peak between August and November (anticipating christmas sales?)

__How did average scores evolve since 2014 ?__
"""

fig = plt.figure(figsize = (15,6))
ax = fig.add_subplot(1, 1, 1)
tmp.loc[(tmp['year'] > 2013) & (tmp['year'] < 2018), ('meta_score', 'year')].groupby('year').mean().plot(ax = ax, xticks=np.arange(2014, 2018, 1))
tmp.loc[(tmp['year'] > 2013) & (tmp['year'] < 2018), ('n_user_score', 'year')].groupby('year').mean().plot(ax = ax, xticks=np.arange(2014, 2018, 1));

"""No big changes

### Best games

__How many titles per console have metacritic score greater than 85?__
"""

tmp.loc[tmp['meta_score'] >= 85].groupby('platform')['title'].count().sort_values(ascending=False)

"""__How many titles per console have user score greater than 85?__"""

tmp.loc[tmp['n_user_score'] >= 85].groupby('platform')['title'].count().sort_values(ascending=False)

"""Let's add a column with the difference between meta and user score"""

tmp['dif'] = tmp['meta_score'] - tmp['n_user_score']

ps4 = tmp.loc[tmp['platform'] == 'PlayStation 4']
xone = tmp.loc[tmp['platform'] == 'Xbox One']
switch = tmp.loc[tmp['platform'] == 'Switch']

"""#### PlayStation 4

__What are the best 20 titles according to metacritic score?__
"""

ps4.sort_values('meta_score', ascending=False).reset_index(drop=True)[['title', 'meta_score', 'n_user_score', 'dif']][:20]

"""For a lot of those titles there's a big difference between what meta critics and users think

__What are the best 20 titles according to user score?__
"""

ps4.sort_values('n_user_score', ascending=False).reset_index(drop=True)[['title', 'n_user_score', 'meta_score', 'dif']][:20]

"""With exception of AO Tennis, meta critics and users scores seem to be similar

__What are the top 10 titles most overrated by metacritic? (user point of view)__
"""

ps4.sort_values('dif', ascending=False)[:10][['title', 'meta_score', 'n_user_score', 'dif']].reset_index(drop=True)

"""__What are the top 10 titles most underrated by metacritic? (user point of view)__"""

ps4.sort_values('dif')[:10][['title', 'meta_score', 'n_user_score', 'dif']].reset_index(drop=True)

"""Let's see more information about AO Tennis"""

ps4.loc[ps4['title'] == 'AO Tennis'].transpose()

"""It's a new game with few critics reviews

### Exclusive games
"""

ps4_list = set(df.loc[df['platform'] == 'PlayStation 4', 'title'])
xone_list = set(df.loc[df['platform'] == 'Xbox One', 'title'])
switch_list = set(df.loc[df['platform'] == 'Switch', 'title'])

"""#### PlayStation 4

__How many exclusive games PlayStation 4 got?__
"""

ps4_exclusives = tmp.loc[tmp['title'].isin(list(ps4_list.difference(xone_list).difference(switch_list))), ('title', 'n_user_score', 'meta_score')].sort_values('n_user_score', ascending=False).reset_index(drop=True)
len(ps4_exclusives)

"""__What are the top 25 exclusives PlayStation 4 games?__"""

ps4_exclusives[:25]

"""__How many exlusive PlayStation 4 games have user score equal or greater than 80 ?__"""

len(ps4_exclusives.loc[ps4_exclusives['n_user_score'] >= 80])

"""#### Xbox One

__How many exclusive games Xbox One got?__
"""

xone_exclusives = tmp.loc[tmp['title'].isin(list(xone_list.difference(ps4_list).difference(switch))), ('title', 'n_user_score', 'meta_score')].sort_values('n_user_score', ascending=False).reset_index(drop=True)
len(xone_exclusives)

"""__What are the top 25 exclusives Xbox One games?__"""

xone_exclusives[:25]

"""__How many exlusive Xbox One games have user score equal or greater than 80 ?__"""

len(xone_exclusives.loc[xone_exclusives['n_user_score'] >= 80])

"""#### Switch

__How many exclusive games Switch got?__
"""

switch_exclusives = tmp.loc[tmp['title'].isin(list(switch_list.difference(ps4_list).difference(xone_list))), ('title', 'n_user_score', 'meta_score')].sort_values('n_user_score', ascending=False).reset_index(drop=True)
len(switch_exclusives)

"""__What are the top 25 exclusives Switch games?__"""

switch_exclusives[:25]

"""__How many exlusive Switch games have user score equal or greater than 80 ?__"""

len(switch_exclusives.loc[switch_exclusives['n_user_score'] >= 80])

"""### Developers

#### PlayStation 4

__Who are the top 10 developers with more released titles?__
"""

ps4.groupby('developer')['title'].count().sort_values(ascending=False)[:10]

"""__Does quantity mean quality?__"""

dev = pd.concat([ps4.groupby('developer')['title'].count(), ps4.groupby('developer')['n_user_score'].mean(), ps4.groupby('developer')['meta_score'].mean()], axis=1)
dev.columns = ['count', 'n_user_score_avg', 'meta_score_avg']
dev.sort_values('count', ascending=False)[:10]

"""It seems that not

__Who are the best 10 developers according to user score (at least 4 released titles)?__
"""

dev.loc[dev['count'] >= 4].sort_values('n_user_score_avg', ascending=False)[:10]

"""__What are the titles that gave them such a good reputation ?__

From Software
"""

ps4.loc[ps4['developer'] == 'From Software', 'title'].reset_index(drop=True)

"""DONTNOD Entertainment"""

ps4.loc[ps4['developer'] == 'DONTNOD Entertainment', 'title'].reset_index(drop=True)

"""__Who are the top 10 developers whose titles are on average more overrated by metacritic (at least 4 released titles) ?__"""

dev = pd.concat([ps4.groupby('developer')['dif'].mean().sort_values(ascending=False), ps4.groupby('developer')['title'].count()], axis=1)
dev.columns = ['dif_avg', 'count']
dev.loc[dev['count'] >= 4].sort_values('dif_avg', ascending=False)[:10]

"""__What are the top 10 EA Sports games according to metacritic?__"""

ea = ps4.loc[ps4['developer'] == 'EA Sports', ['title', 'meta_score', 'n_user_score']].sort_values('meta_score', ascending=False)[:10]
ea.set_index('title').plot.bar(figsize=(14, 6));

"""__Who are the top 10 developers whose titles are on average more underrated by metacritic (at least 4 released titles)?__"""

dev.loc[dev['count'] >= 4].sort_values('dif_avg')[:10]

ps4.loc[ps4['developer'] == 'HB Studios Multimedia', 'title'].reset_index(drop=True)

ps4.loc[ps4['developer'] == 'Acquire', 'title'].reset_index(drop=True)

"""### Ratings

__How many titles per rating category?__
"""

df['rating'].value_counts().plot.bar(figsize=(12, 6), rot=0);

"""E: Everyone
<br/>E+10: Everyone +10
<br/>T: Teen +13
<br/>M: Mature +17

__Which console is more "family" oriented?__
"""

qty = df.loc[(df['rating'].isnull() == False) & (df['rating'] != 'RP')].groupby('platform')['title'].count()
#((df.loc[df['rating'] != 'RP'].groupby(['platform', 'rating'])['title'].count().unstack().transpose() / qty) * 100).plot.bar(figsize=(12, 6), rot=0);
rat = (df.loc[df['rating'] != 'RP'].groupby(['platform', 'rating'])['title'].count().unstack().transpose() / qty) * 100
rat = rat[['PlayStation 4', 'Xbox One', 'Switch']]

fig = plt.figure(figsize = (10,6))
ax = fig.add_subplot(1, 1, 1)
rat.iloc[0].plot.bar(ax=ax, color='beige', edgecolor='white', label=rat.index[0]);
rat.iloc[1].plot.bar(ax=ax, bottom=rat.iloc[0], color='navajowhite', edgecolor='white', label=rat.index[1]);
rat.iloc[3].plot.bar(ax=ax, bottom=rat.iloc[:2].sum().values, color='lightsalmon', edgecolor='white', label=rat.index[3]);
rat.iloc[2].plot.bar(ax=ax, bottom=(rat.iloc[:2].sum() + rat.iloc[3]).values, color='firebrick', edgecolor='white', label=rat.index[2], rot=0);
ax.legend(loc='upper left', bbox_to_anchor=(1, 1), ncol=1);

"""Switch has in proportion more games suited for everyone

__Which category has the best games ?__
"""

tmp.loc[(tmp['rating'].isnull() == False) & (tmp['rating'] != 'RP')].groupby('rating')['n_user_score'].mean().sort_values(ascending=False).plot.bar(figsize=(12, 6), rot=0);

"""Mature category seems to has an advantage"""

